name: Python-bot-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  
jobs:
  build:
    name: Python Bot-Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.PYTHON_DISCORD_TOKEN }}" >> .env
          cat .env
          echo "success create .env : ${{ secrets.PYTHON_DISCORD_TOKEN }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          
      - name: Run Python
        run: |
          python3 main.py
